export const cartSimilarItems = [
    {
        id: 8,
        title: "Trek Marlin 4 Matte Anthracite ATB 29 2022",
        price: 28000,
        oldPrice: null,
        available: true,
        country: {
            name: "Італія",
            isoCode: "IT",
            flag: "/images/flags/it.avif",
        },
        brand: "trek",
        category: "doubleSuspension",
        material: "carbon",
        color: "#7F7F7F",
        preview: "/images/bicycles/trek_marlin_4_matte_anthracite_atb_29_2022/img_1.avif",
        photos: [
            "/images/bicycles/trek_marlin_4_matte_anthracite_atb_29_2022/img_1.avif",
            "",
            "",
            "",
        ],
    },
    {
        id: 9,
        title: "Orbea RUDE 10 Black 2022",
        price: 35000,
        oldPrice: null,
        available: true,
        country: {
            name: "Іспанія",
            isoCode: "ES",
            flag: "/images/flags/es.avif",
        },
        brand: "bmc",
        category: "child",
        material: "steel",
        color: "#000000",
        preview: "/images/bicycles/orbea_rude_10_black_2022/img_1.avif",
        photos: [
            "/images/bicycles/orbea_rude_10_black_2022/img_1.avif",
            "",
            "",
            "",
        ],
    },
    {
        id: 10,
        title: "Trek Marlin 5 Lithium Grey Chrome ATB 27.5 2022",
        price: 76000,
        oldPrice: 84000,
        available: true,
        country: {
            name: "Америка",
            isoCode: "US",
            flag: "/images/flags/us.avif",
        },
        brand: "trek",
        category: "mountain",
        material: "carbon",
        color: "#7F7F7F",
        preview: "/images/bicycles/trek_marlin_5_lithium_grey_chrome_atb_27_5_2022/img_1.avif",
        photos: [
            "/images/bicycles/trek_marlin_5_lithium_grey_chrome_atb_27_5_2022/img_1.avif",
            "",
            "",
            "",
        ],
    },
    {
        id: 11,
        title: "Trek Marlin 4 Aloha ATB 27.5 2022",
        price: 82000,
        oldPrice: null,
        available: true,
        country: {
            name: "Америка",
            isoCode: "US",
            flag: "/images/flags/us.avif",
        },
        brand: "trek",
        category: "mountain",
        material: "aluminum",
        color: "#38D5C8",
        preview: "/images/bicycles/trek_marlin_4_aloha_atb_27_5_2022/img_1.avif",
        photos: [
            "/images/bicycles/trek_marlin_4_aloha_atb_27_5_2022/img_1.avif",
            "",
            "",
            "",
        ],
    },
    {
        id: 12,
        title: "Scott 700 SL 2014",
        price: 46500,
        oldPrice: null,
        available: true,
        country: {
            name: "Іспанія",
            isoCode: "ES",
            flag: "/images/flags/es.avif",
        },
        brand: "cipolini",
        category: "mountain",
        material: "steel",
        color: "#FE7E56",
        preview: "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
        photos: [
            "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
            "",
            "",
            "",
        ],
    },
]