import {ICatalogPage} from "../types.ts";

export const catalogPage1: ICatalogPage  = {
    currentPage: 1,
    totalPages: 10,
    nextPageUrl: "#",
    prevPageUrl: null,
    data: [
        {
            id: 1,
            title: "Look 977 BLACK FLUO YELLOW GREEN XT 2x11S AMC 2018",
            price: 14500,
            available: true,
            country: {
                name: "Швеція",
                isoCode: "SE",
                flag: "/images/flags/se.avif",
            },
            brand: "bmc",
            category: "mountain",
            material: "steel",
            color: "#000",
            preview: "/images/bicycles/look_977_black_fluo_yellow_green_xt_2x11s_amc_2018/img_1.avif",
            photos: [
                "/images/bicycles/look_977_black_fluo_yellow_green_xt_2x11s_amc_2018/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 2,
            title: "Trek Dual Sport 2 Mulsanne Hybd 2022",
            price: 22300,
            available: false,
            country: {
                name: "Італія",
                isoCode: "SE",
                flag: "/images/flags/it.avif",
            },
            brand: "trek",
            category: "city",
            material: "carbon",
            color: "#49423D",
            preview: "/images/bicycles/trek_dual_sport_2_mulsanne_hybd_2022/img_1.avif",
            photos: [
                "/images/bicycles/trek_dual_sport_2_mulsanne_hybd_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 3,
            title: "Orbea ALMA H30 2021",
            price: 43000,
            available: true,
            country: {
                name: "Іспанія",
                isoCode: "ES",
                flag: "/images/flags/es.avif",
            },
            brand: "bianci",
            category: "electric",
            material: "aluminum",
            color: "#E5E4E2",
            preview: "/images/bicycles/orbea_alma_h30_2021/img_1.avif",
            photos: [
                "/images/bicycles/orbea_alma_h30_2021/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 4,
            title: "Trek Fx 3 Disc Dnister Black HYBD 2022",
            price: 32500,
            available: true,
            country: {
                name: "Італія",
                isoCode: "IT",
                flag: "/images/flags/it.avif",
            },
            brand: "trek",
            category: "gravel",
            material: "carbon",
            color: "#353839",
            preview: "/images/bicycles/trek_fx_3_disc_dnister_black_hybd_2022/img_1.avif",
            photos: [
                "/images/bicycles/trek_fx_3_disc_dnister_black_hybd_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 5,
            title: "Scott Scale 700 RS 2016",
            price: 16000,
            available: false,
            country: {
                name: "Франція",
                isoCode: "FR",
                flag: "/images/flags/fr.avif",
            },
            brand: "colnago",
            category: "triathlon",
            material: "aluminum",
            color: "#25FD3C",
            preview: "/images/bicycles/scott_scale_700_rs_2016/img_1.avif",
            photos: [
                "/images/bicycles/scott_scale_700_rs_2016/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 6,
            title: "Look 979 BLACK FLUO YELLOW GREEN XT 2x11S AMC 2018",
            price: 62000,
            available: false,
            country: {
                name: "Італія",
                isoCode: "IT",
                flag: "/images/flags/it.avif",
            },
            brand: "merida",
            category: "city",
            material: "carbon",
            color: "#061E42",
            preview: "/images/bicycles/look_977_black_fluo_yellow_green_xt_2x11s_amc_2018/img_1.avif",
            photos: [
                "/images/bicycles/look_977_black_fluo_yellow_green_xt_2x11s_amc_2018/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 7,
            title: "Scott Scale 700 SL 2016",
            price: 75600,
            available: true,
            country: {
                name: "Іспанія",
                isoCode: "ES",
                flag: "/images/flags/es.avif",
            },
            brand: "cipolini",
            category: "mountain",
            material: "steel",
            color: "#FE7E56",
            preview: "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
            photos: [
                "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 8,
            title: "Trek Marlin 4 Matte Anthracite ATB 29 2022",
            price: 28000,
            available: true,
            country: {
                name: "Італія",
                isoCode: "IT",
                flag: "/images/flags/it.avif",
            },
            brand: "trek",
            category: "doubleSuspension",
            material: "carbon",
            color: "#7F7F7F",
            preview: "/images/bicycles/trek_marlin_4_matte_anthracite_atb_29_2022/img_1.avif",
            photos: [
                "/images/bicycles/trek_marlin_4_matte_anthracite_atb_29_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 9,
            title: "Orbea RUDE 10 Black 2022",
            price: 35000,
            available: true,
            country: {
                name: "Іспанія",
                isoCode: "ES",
                flag: "/images/flags/es.avif",
            },
            brand: "bmc",
            category: "child",
            material: "steel",
            color: "#000000",
            preview: "/images/bicycles/orbea_rude_10_black_2022/img_1.avif",
            photos: [
                "/images/bicycles/orbea_rude_10_black_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 10,
            title: "Trek Marlin 5 Lithium Grey Chrome ATB 27.5 2022",
            price: 76000,
            available: true,
            country: {
                name: "Америка",
                isoCode: "US",
                flag: "/images/flags/us.avif",
            },
            brand: "trek",
            category: "mountain",
            material: "carbon",
            color: "#7F7F7F",
            preview: "/images/bicycles/trek_marlin_5_lithium_grey_chrome_atb_27_5_2022/img_1.avif",
            photos: [
                "/images/bicycles/trek_marlin_5_lithium_grey_chrome_atb_27_5_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 11,
            title: "Trek Marlin 4 Aloha ATB 27.5 2022",
            price: 82000,
            available: true,
            country: {
                name: "Америка",
                isoCode: "US",
                flag: "/images/flags/us.avif",
            },
            brand: "trek",
            category: "mountain",
            material: "aluminum",
            color: "#38D5C8",
            preview: "/images/bicycles/trek_marlin_4_aloha_atb_27_5_2022/img_1.avif",
            photos: [
                "/images/bicycles/trek_marlin_4_aloha_atb_27_5_2022/img_1.avif",
                "",
                "",
                "",
            ],
        },
        {
            id: 12,
            title: "Scott 700 SL 2014",
            price: 46500,
            available: true,
            country: {
                name: "Іспанія",
                isoCode: "ES",
                flag: "/images/flags/es.avif",
            },
            brand: "cipolini",
            category: "mountain",
            material: "steel",
            color: "#FE7E56",
            preview: "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
            photos: [
                "/images/bicycles/scott_scale_700_sl_2016/img_1.avif",
                "",
                "",
                "",
            ],
        },
    ]
}